### ISSUE TITLE
Small task list so its not forgotten

### ISSUE THREAD

**Issue by olymk2** [olymk2/maidstone-hackspace#4]
- [ ] Fix last login date
- [ ] Fix join date
- [ ] Badge icons
- [ ] membership graphics
- [ ] change email address
